
-- CREACIÓN DE TABLAS

CREATE TABLE SUCURSALES
   (	
 	NUM_SUCURSAL NUMERIC(1), 
	NOMBRE VARCHAR(40) NOT NULL, 
	AREA VARCHAR(35) NOT NULL, 
	PAIS VARCHAR(25) NOT NULL,
	CONSTRAINT sucursales_pk PRIMARY KEY (NUM_SUCURSAL),
	CONSTRAINT sucursales_u UNIQUE (NOMBRE)
   );

CREATE TABLE DIRECTORES
   (	
  	CODIGO VARCHAR(6),
	SUCURSAL NUMERIC(1),
	NOMBRE VARCHAR(40) NOT NULL, 
	AREA_TRABAJO VARCHAR(35) NOT NULL, 
	SALARIO NUMERIC(10,2) DEFAULT 4500 NOT NULL, 
	TELEFONO VARCHAR(15) NOT NULL, 
	PAIS VARCHAR(25),
	CONSTRAINT dic_pk PRIMARY KEY (CODIGO),
	CONSTRAINT dic_fk FOREIGN KEY (SUCURSAL) REFERENCES SUCURSALES(NUM_SUCURSAL),
	CONSTRAINT dic_u UNIQUE (TELEFONO),
	CONSTRAINT dic_u2 UNIQUE (SUCURSAL)
   );	

CREATE TABLE AGENTES
   (	
  	CODIGO VARCHAR(6),
	SUCURSAL NUMERIC(1),
	NOMBRE VARCHAR(40) NOT NULL, 
	AREA_TRABAJO VARCHAR(35) NOT NULL, 
	COMISION NUMERIC(10,2) DEFAULT 0.10 NOT NULL, 
	TELEFONO VARCHAR(15) NOT NULL, 
	PAIS VARCHAR(25),
	CONSTRAINT agentes_pk PRIMARY KEY (CODIGO),
	CONSTRAINT agentes_fk FOREIGN KEY (SUCURSAL) REFERENCES SUCURSALES(NUM_SUCURSAL),
	CONSTRAINT agentes_u UNIQUE (TELEFONO)
   );

CREATE TABLE CLIENTES 
   (	
 	 CODIGO VARCHAR(6), 
	NOMBRE VARCHAR(40) NOT NULL, 
	CIUDAD VARCHAR(35), 
	AREA_TRABAJO VARCHAR(35) NOT NULL, 
	PAIS VARCHAR(20) NOT NULL, 
	NIVEL NUMERIC(1), 
	TELEFONO VARCHAR(17) NOT NULL, 
	CODIGO_AGENTE VARCHAR(6),
  	CONSTRAINT clientes_pk PRIMARY KEY (CODIGO),
 	CONSTRAINT clientes_fk FOREIGN KEY (CODIGO_AGENTE) REFERENCES AGENTES(CODIGO),
  	CONSTRAINT clientes_u UNIQUE (TELEFONO),
  	CONSTRAINT clientes_u2 UNIQUE (NOMBRE)
    );

CREATE TABLE PEDIDOS
   (
  	NUM_PEDIDO NUMERIC(6), 
	PRECIO_PEDIDO NUMERIC(12,2) NOT NULL, 
	SENAL NUMERIC(12,2) DEFAULT 0 NOT NULL, 
	FECHA_PEDIDO DATE NOT NULL, 
	CODIGO_CLIENTE VARCHAR(6), 
	CODIGO_AGENTE VARCHAR(6), 
	DESCRIPCION_PEDIDO VARCHAR(60) NOT NULL,
	CONSTRAINT pedidos_pk PRIMARY KEY (NUM_PEDIDO),
	CONSTRAINT pedidos_fk1 FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO),
	CONSTRAINT pedidos_fk2 FOREIGN KEY (CODIGO_AGENTE) REFERENCES AGENTES(CODIGO),
	CONSTRAINT pedidos_c CHECK (to_char(fecha_pedido,'YYYY-MM-DD') >= '2006-01-01')
   );
